future4code/barros-Diego-Santos

modulo1/projeto-onboarding/aprendizados.md

primeira mudança

---

modulo1/Variaveis/aula-variaveis/index.html
modulo1/Variaveis/aula-variaveis/index.js
modulo1/Variaveis/template_javascript/index.html
modulo1/Variaveis/template_javascript/index.js

variaveis-exercicio1

---

modulo1/operadores/template_javascript/index.html
modulo1/operadores/template_javascript/index.js

- tudo
- nao terminei o desafio opcional, parei no 3° mas vou esta terminando e reenviando.

operadores-atividade-14/04

---

modulo1/strings-arrays/template_javascript/index.html
modulo1/strings-arrays/template_javascript/index.js

String-Arrays

---

modulo1/objetos/index.html
modulo1/objetos/index.js

exercicos-objetos

---

modulo1/projeto-blackjack/desafio.js
modulo1/projeto-blackjack/index.html
modulo1/projeto-blackjack/naoMexer.js
modulo1/projeto-blackjack/nossoJogo.js

- tudo
- nao fiz o desafio ainda, mas pretendo fazer ate o ultimo momento

Projeto-BlackJack

---

modulo1/revisao-js/lista-revisao-js/exercicios.js

- ate o exercicio 13B
- os demais depois do que funciona :)

exercicio de revisao feito ate o 13B

---

modulo1/revisao-js/lista-revisao-js/exercicios.js

- ate o exercicio 14
- 15A e 15B

exercicio de revisao feito ate o 14

---

modulo2/agil/kanban.txt

Processos-ageis

---

modulo3/estados-insta4/insta4/src/App.js
modulo3/estados-insta4/insta4/src/components/Post/Post.js
modulo3/estados-insta4/insta4/src/style.js

- Oque foi pedido
- https://enormous-throat.surge.sh/

Exercicio 2: Renderizacao de Listas 2 / feito

---

modulo3/postman/PlayList.postman_collection.json

Metodos de criacão e remoção da playlist

---

modulo5/revisao-javascript-backend/backend/exercicio1/index.js
modulo5/revisao-javascript-backend/backend/exercicio2/index.js
modulo5/revisao-javascript-backend/backend/exercicio3/index.js
modulo5/revisao-javascript-backend/backend/exercicio4/exercicio.js

feat: exercicio 1 feito

---

modulo5/intro-typescript/.gitignore
modulo5/intro-typescript/package-lock.json
modulo5/intro-typescript/package.json
modulo5/intro-typescript/src/exercicio1/exercicio1.ts
modulo5/intro-typescript/src/exercicio2/exercicio2.ts
modulo5/intro-typescript/src/exercicio3/exercicio3.ts
modulo5/intro-typescript/src/exercicio4/exercicio4.ts
modulo5/intro-typescript/src/exercicio5/exercicio5.ts
modulo5/intro-typescript/tsconfig.json

feat: Todos exercicios concluidos

---

modulo5/node-package-json/exercicio-1/index.js
modulo5/node-package-json/exercicio-1/package.json
modulo5/node-package-json/exercicio-2/index.js
modulo5/node-package-json/exercicio-2/package.json
modulo5/node-package-json/exercicio-3/index.js
modulo5/node-package-json/exercicio-3/package.json

feat: Exercicio feito e completo

---

modulo5/lista-typescript/package-lock.json
modulo5/lista-typescript/package.json
modulo5/lista-typescript/src/exercicio1/exercicio1.ts
modulo5/lista-typescript/src/exercicio2/exercicio2.ts
modulo5/lista-typescript/src/exercicio3/exercicio3.ts
modulo5/lista-typescript/src/exercicio4/exercicio4.ts
modulo5/lista-typescript/src/exercicio5/exercicio5.ts
modulo5/lista-typescript/src/exercicio6/exercicio6.ts
modulo5/lista-typescript/src/exercicio7/exercicio7.ts
modulo5/lista-typescript/src/exercicio8/exercicio8.ts
modulo5/lista-typescript/src/userInput.ts
modulo5/lista-typescript/tsconfig.json

feat:lista feita ate o exercicio 6

---

modulo5/fluxo-de-dados-backend/.gitignore
modulo5/fluxo-de-dados-backend/package-lock.json
modulo5/fluxo-de-dados-backend/package.json
modulo5/fluxo-de-dados-backend/src/data.ts
modulo5/fluxo-de-dados-backend/src/index.ts
modulo5/fluxo-de-dados-backend/src/type.ts
modulo5/fluxo-de-dados-backend/tsconfig.json

feat: Exercicio de 1 a 4

---

modulo5/aprofundamento-express/.gitignore
modulo5/aprofundamento-express/package-lock.json
modulo5/aprofundamento-express/package.json
modulo5/aprofundamento-express/src/index.ts
modulo5/aprofundamento-express/tsconfig.json

- Link da Documentação Abaixo ... 
- https://documenter.getpostman.com/view/22376175/2s8YRdsFqD

feat: aprofudamento-express, feito ate o exercicio 5

---

modulo5/intro-express/.gitignore
modulo5/intro-express/package-lock.json
modulo5/intro-express/package.json
modulo5/intro-express/src/index.ts
modulo5/intro-express/tsconfig.json

feat: Exercicio feitos, somente ate o 8

---

modulo5/aprofundamento-typescript/.gitignore
modulo5/aprofundamento-typescript/package-lock.json
modulo5/aprofundamento-typescript/package.json
modulo5/aprofundamento-typescript/src/exercicio1/exercicio1.ts
modulo5/aprofundamento-typescript/src/exercicio2/exercicio2.ts
modulo5/aprofundamento-typescript/src/exercicio3/exercicio3.js
modulo5/aprofundamento-typescript/src/exercicio3/exercicio3.ts
modulo5/aprofundamento-typescript/src/exercicio4/exercicio4.js
modulo5/aprofundamento-typescript/src/exercicio4/exercicio4.ts
modulo5/aprofundamento-typescript/tsconfig.json

Feat: Exercicio feito

---

modulo5/apis-rest/.gitignore
modulo5/apis-rest/package-lock.json
modulo5/apis-rest/package.json
modulo5/apis-rest/src/data.ts
modulo5/apis-rest/src/index.ts
modulo5/apis-rest/tsconfig.json

- link da documentacao 
- https://documenter.getpostman.com/view/22376175/2s8YYJqN5i

Feat: inicializacao do exercicio apis-rest

---

modulo5/aprofundamento-sql/texto.md

feat: Aprofundamento SQL

---

modulo5/relacoes-sql/relacoesSQL.md

relacoes-sql

---

modulo5/knex-js/.gitignore
modulo5/knex-js/package.json
modulo5/knex-js/src/index.ts
modulo5/knex-js/tsconfig.json

feat: Instalacoes iniciais

---

modulo5/classes-encapsulamento/.gitignore
modulo5/classes-encapsulamento/package-lock.json
modulo5/classes-encapsulamento/package.json
modulo5/classes-encapsulamento/requests.rest
modulo5/classes-encapsulamento/src/class/Product.ts
modulo5/classes-encapsulamento/src/class/ProductDB.ts
modulo5/classes-encapsulamento/src/class/Purchase.ts
modulo5/classes-encapsulamento/src/class/PurchaseDB.ts
modulo5/classes-encapsulamento/src/class/User.ts
modulo5/classes-encapsulamento/src/class/UserDB.ts
modulo5/classes-encapsulamento/src/database/connection.ts
modulo5/classes-encapsulamento/src/database/data.ts
modulo5/classes-encapsulamento/src/database/migrations.ts
modulo5/classes-encapsulamento/src/database/tableNames.ts
modulo5/classes-encapsulamento/src/endpoints/createProduct.ts
modulo5/classes-encapsulamento/src/endpoints/createPurchase.ts
modulo5/classes-encapsulamento/src/endpoints/createUser.ts
modulo5/classes-encapsulamento/src/endpoints/getProducts.ts
modulo5/classes-encapsulamento/src/endpoints/getUserPurchases.ts
modulo5/classes-encapsulamento/src/endpoints/getUsers.ts
modulo5/classes-encapsulamento/src/endpoints/ping.ts
modulo5/classes-encapsulamento/src/index.ts
modulo5/classes-encapsulamento/src/models/Product.ts
modulo5/classes-encapsulamento/src/models/Purchase.ts
modulo5/classes-encapsulamento/src/models/User.ts
modulo5/classes-encapsulamento/tsconfig.json

FEAT: classes e encapsulamento

---

modulo5/heranca-encapsulamento/.gitignore
modulo5/heranca-encapsulamento/package-lock.json
modulo5/heranca-encapsulamento/package.json
modulo5/heranca-encapsulamento/requests.rest
modulo5/heranca-encapsulamento/src/database/BaseDataBase.ts
modulo5/heranca-encapsulamento/src/database/UserDataBase.ts
modulo5/heranca-encapsulamento/src/database/connection.ts
modulo5/heranca-encapsulamento/src/database/data.ts
modulo5/heranca-encapsulamento/src/database/migrations.ts
modulo5/heranca-encapsulamento/src/database/tableNames.ts
modulo5/heranca-encapsulamento/src/endpoints/createProduct.ts
modulo5/heranca-encapsulamento/src/endpoints/createPurchase.ts
modulo5/heranca-encapsulamento/src/endpoints/createUser.ts
modulo5/heranca-encapsulamento/src/endpoints/getProducts.ts
modulo5/heranca-encapsulamento/src/endpoints/getUserPurchases.ts
modulo5/heranca-encapsulamento/src/endpoints/getUsers.ts
modulo5/heranca-encapsulamento/src/endpoints/ping.ts
modulo5/heranca-encapsulamento/src/index.ts
modulo5/heranca-encapsulamento/src/models/Product.ts
modulo5/heranca-encapsulamento/src/models/Purchase.ts
modulo5/heranca-encapsulamento/src/models/User.ts
modulo5/heranca-encapsulamento/tsconfig.json

Incompleto

---

modulo6/arquitetura-de-software-1/.gitignore
modulo6/arquitetura-de-software-1/package.json
modulo6/arquitetura-de-software-1/request.rest
modulo6/arquitetura-de-software-1/src/app.ts
modulo6/arquitetura-de-software-1/src/business/UserBusiness.ts
modulo6/arquitetura-de-software-1/src/controller/UserController.ts
modulo6/arquitetura-de-software-1/src/data/BaseDatabase.ts
modulo6/arquitetura-de-software-1/src/data/UserDb.ts
modulo6/arquitetura-de-software-1/src/index.ts
modulo6/arquitetura-de-software-1/src/types/UserType.ts
modulo6/arquitetura-de-software-1/tsconfig.json

Feat: concluido

---

modulo6/arquitetura-de-software-2/labeflix/.gitignore
modulo6/arquitetura-de-software-2/labeflix/package-lock.json
modulo6/arquitetura-de-software-2/labeflix/package.json
modulo6/arquitetura-de-software-2/labeflix/queries.sql
modulo6/arquitetura-de-software-2/labeflix/request.rest
modulo6/arquitetura-de-software-2/labeflix/src/app.ts
modulo6/arquitetura-de-software-2/labeflix/src/business/MovieBusiness.ts
modulo6/arquitetura-de-software-2/labeflix/src/business/UserBusiness.ts
modulo6/arquitetura-de-software-2/labeflix/src/controller/MovieController.ts
modulo6/arquitetura-de-software-2/labeflix/src/controller/UserController.ts
modulo6/arquitetura-de-software-2/labeflix/src/data/BaseDatabase.ts
modulo6/arquitetura-de-software-2/labeflix/src/data/MovieDatabase.ts
modulo6/arquitetura-de-software-2/labeflix/src/data/UserDatabase.ts
modulo6/arquitetura-de-software-2/labeflix/src/index.ts
modulo6/arquitetura-de-software-2/labeflix/src/routes/movieRouter.ts
modulo6/arquitetura-de-software-2/labeflix/src/routes/userRouter.ts
modulo6/arquitetura-de-software-2/labeflix/src/types/User.ts
modulo6/arquitetura-de-software-2/labeflix/tsconfig.json

feito arquitetura-software-2

---

modulo6/arquitetura-software-3/.gitignore
modulo6/arquitetura-software-3/package-lock.json
modulo6/arquitetura-software-3/package.json
modulo6/arquitetura-software-3/queries.sql
modulo6/arquitetura-software-3/request.rest
modulo6/arquitetura-software-3/src/app.ts
modulo6/arquitetura-software-3/src/business/MovieBusiness.ts
modulo6/arquitetura-software-3/src/business/UserBusiness.ts
modulo6/arquitetura-software-3/src/controller/MovieController.ts
modulo6/arquitetura-software-3/src/controller/UserController.ts
modulo6/arquitetura-software-3/src/data/BaseDatabase.ts
modulo6/arquitetura-software-3/src/data/MovieDatabase.ts
modulo6/arquitetura-software-3/src/data/UserDatabase.ts
modulo6/arquitetura-software-3/src/error/CustomError.ts
modulo6/arquitetura-software-3/src/error/MovieErro.ts
modulo6/arquitetura-software-3/src/error/UserError.ts
modulo6/arquitetura-software-3/src/index.ts
modulo6/arquitetura-software-3/src/model/MovieDTO.ts
modulo6/arquitetura-software-3/src/model/UserDTO.ts
modulo6/arquitetura-software-3/src/routes/movieRouter.ts
modulo6/arquitetura-software-3/src/routes/userRouter.ts
modulo6/arquitetura-software-3/src/services/generateId.ts
modulo6/arquitetura-software-3/tsconfig.json

arquitetura-software-3

---

modulo6/introducao-autenticacao/.gitignore
modulo6/introducao-autenticacao/Respostas.md
modulo6/introducao-autenticacao/package-lock.json
modulo6/introducao-autenticacao/package.json
modulo6/introducao-autenticacao/requests.rest
modulo6/introducao-autenticacao/src/business/UserBusiness.ts
modulo6/introducao-autenticacao/src/controller/UserController.ts
modulo6/introducao-autenticacao/src/controller/app.ts
modulo6/introducao-autenticacao/src/controller/userRouter.ts
modulo6/introducao-autenticacao/src/data/BaseDatabase.ts
modulo6/introducao-autenticacao/src/data/UserDatabase.ts
modulo6/introducao-autenticacao/src/error/customError.ts
modulo6/introducao-autenticacao/src/index.ts
modulo6/introducao-autenticacao/src/model/user.ts
modulo6/introducao-autenticacao/src/services/Authenticator.ts
modulo6/introducao-autenticacao/src/services/IdGenerator.ts
modulo6/introducao-autenticacao/tables.sql
modulo6/introducao-autenticacao/tsconfig.json

FEAT: Exercicio concluido

---

modulo6/criptografia/.gitignore
modulo6/criptografia/package-lock.json
modulo6/criptografia/package.json
modulo6/criptografia/requests.rest
modulo6/criptografia/respostas.md
modulo6/criptografia/src/business/UserBusiness.ts
modulo6/criptografia/src/controller/UserController.ts
modulo6/criptografia/src/controller/app.ts
modulo6/criptografia/src/controller/userRouter.ts
modulo6/criptografia/src/data/BaseDatabase.ts
modulo6/criptografia/src/data/UserDatabase.ts
modulo6/criptografia/src/error/customError.ts
modulo6/criptografia/src/index.ts
modulo6/criptografia/src/model/user.ts
modulo6/criptografia/src/services/HashManager.ts
modulo6/criptografia/src/services/IdGenerator.ts
modulo6/criptografia/src/services/TokenGenerator.ts
modulo6/criptografia/tables.sql
modulo6/criptografia/tsconfig.json

criptografia

---

modulo7/testes-unitatios-moks/.gitignore
modulo7/testes-unitatios-moks/jest.config.js
modulo7/testes-unitatios-moks/package-lock.json
modulo7/testes-unitatios-moks/package.json
modulo7/testes-unitatios-moks/src/funcs/performAttack.ts
modulo7/testes-unitatios-moks/src/funcs/validateCharacter.ts
modulo7/testes-unitatios-moks/src/model.ts
modulo7/testes-unitatios-moks/tests/testPerformAttack.test.ts
modulo7/testes-unitatios-moks/tests/testValidateCharacter.test.ts
modulo7/testes-unitatios-moks/tsconfig.json

teste-unitarios-moks

---

modulo7/testes-backend/.gitignore
modulo7/testes-backend/addUsers.sql
modulo7/testes-backend/jest.config.js
modulo7/testes-backend/package-lock.json
modulo7/testes-backend/package.json
modulo7/testes-backend/request.rest
modulo7/testes-backend/src/business/UserBusiness.ts
modulo7/testes-backend/src/business/UserRepository.ts
modulo7/testes-backend/src/controller/UserController.ts
modulo7/testes-backend/src/data/BaseDatabase.ts
modulo7/testes-backend/src/data/UserDatabase.ts
modulo7/testes-backend/src/error/CustomError.ts
modulo7/testes-backend/src/index.ts
modulo7/testes-backend/src/model/UserModel.ts
modulo7/testes-backend/src/router/userRouter.ts
modulo7/testes-backend/src/services/IdGenerator.ts
modulo7/testes-backend/tests/business/UserBusiness.test.ts
modulo7/testes-backend/tests/mocks/UserDatabaseMock.ts
modulo7/testes-backend/tests/mocks/UserMock.ts
modulo7/testes-backend/tsconfig.json

Testes-backend
